name: "Warren - Docker Containers"
description: "Start docker-compose for integration tests"
branding:
  icon: "layers"
  color: "red"
inputs:
  docker-compose-file:
    description: "The docker-compose file path (absolute, relative or pattern paths are acceptable)"
    required: true
runs:
  using: composite
  steps:
    - name: "Stop all containers"
      shell: bash
      run: |
        containers=$(docker ps -aq)
        if [ -n "$containers" ]; then
          docker stop $containers || true
        else
          echo "No containers to stop."
        fi

    - name: "Remove all containers"
      shell: bash
      run: |
        containers=$(docker ps -aq)
        if [ -n "$containers" ]; then
          docker rm $containers || true
        else
          echo "No containers to remove."
        fi

    - name: "Stop Docker Dependencies"
      shell: bash
      env:
        DOCKER_COMPOSE_FILE: ${{ inputs.docker-compose-file }}
      run: |
        if command -v docker-compose &> /dev/null; then
          docker-compose -f "$DOCKER_COMPOSE_FILE" down || true
        else
          docker compose -f "$DOCKER_COMPOSE_FILE" down || true
        fi

    - name: "Start Docker Dependencies"
      shell: bash
      env:
        DOCKER_COMPOSE_FILE: ${{ inputs.docker-compose-file }}
      run: |
        if command -v docker-compose &> /dev/null; then
          docker-compose -f "$DOCKER_COMPOSE_FILE" up -d
        else
          docker compose -f "$DOCKER_COMPOSE_FILE" up -d
        fi

    - name: "Wait for Docker Dependencies"
      shell: bash
      run: sleep 10s
